import type { Metadata } from "next";
import "../styles/styles.scss";
import Header from "@/components/features/header/Header";
import Providers from "../components/prooviders/providers";

export const metadata: Metadata = {
  title: "Test tecnical front",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
